services:
  # -------------------------
  # PostgreSQL Database
  # -------------------------
  db:
    image: postgres:latest
    container_name: PostgreSQL_DB
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER_SECRET}
      POSTGRES_PASSWORD: ${DB_PASSWORD_SECRET}
      POSTGRES_DB: ${DB_NAME_SECRET}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - zoo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER_SECRET} -d ${DB_NAME_SECRET}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  # -------------------------
  # pgAdmin
  # -------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminApp
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - zoo_network

  # -------------------------
  # Python importer
  # -------------------------
  importer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data_importer
    working_dir: /app
    volumes:
      - ./:/app
    command: ["python", "-u", "stage_1/Programing/generate_data.py"]
    environment:
      DB_NAME: ${DB_NAME_SECRET}
      DB_USER: ${DB_USER_SECRET}
      DB_PASSWORD: ${DB_PASSWORD_SECRET}
      DB_HOST: db
      DB_PORT: 5432
      DATASET_DIR: /app/dataset
    depends_on:
      db:
        condition: service_healthy
    networks:
      - zoo_network
    profiles:
      - import

# -------------------------
# Volumes
# ------------------------
volumes:
  postgres_data:
  pgadmin_data:

networks:
  zoo_network: