CREATE TABLE PERSON
(
  ID INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  DateOfBirth DATE NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE TEAM
(
  TeamCode VARCHAR(3) NOT NULL,
  CountryName VARCHAR(100) NOT NULL,
  Confederation VARCHAR(50) NOT NULL,
  PRIMARY KEY (TeamCode)
);

CREATE TABLE PLAYER
(
  Position VARCHAR(50) NOT NULL,
  TeamCode VARCHAR(3) NOT NULL,
  ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (TeamCode) REFERENCES TEAM(TeamCode),
  FOREIGN KEY (ID) REFERENCES PERSON(ID)
);

CREATE TABLE REFEREE
(
  Years_of_experience INT NOT NULL CHECK (Years_of_experience >= 0),
  ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES PERSON(ID)
);

CREATE TABLE STADIUM
(
  StadiumID INT NOT NULL,
  City VARCHAR(100) NOT NULL,
  Name VARCHAR(100) NOT NULL,
  Capacity INT NOT NULL CHECK (Capacity > 0),
  PRIMARY KEY (StadiumID)
);

CREATE TABLE MATCHES
(
  MatchID INT NOT NULL,
  MatchDate DATE NOT NULL,
  Stage VARCHAR(50) NOT NULL,
  HomeTeamCode VARCHAR(3) NOT NULL,
  AwayTeamCode VARCHAR(3) NOT NULL,
  StadiumID INT NOT NULL,
  RefereeID INT NOT NULL,
  PRIMARY KEY (MatchID),
  FOREIGN KEY (HomeTeamCode) REFERENCES TEAM(TeamCode),
  FOREIGN KEY (AwayTeamCode) REFERENCES TEAM(TeamCode),
  FOREIGN KEY (StadiumID) REFERENCES STADIUM(StadiumID),
  FOREIGN KEY (RefereeID) REFERENCES REFEREE(ID),
  CHECK (HomeTeamCode != AwayTeamCode)
);

CREATE TABLE MATCH_EVENT
(
  Minute INT NOT NULL CHECK (Minute > 0 AND Minute <= 130),
  EventType VARCHAR(50) NOT NULL,
  MatchID INT NOT NULL,
  PlayerID INT NOT NULL,
  PRIMARY KEY (Minute, MatchID),
  FOREIGN KEY (MatchID) REFERENCES MATCHES(MatchID),
  FOREIGN KEY (PlayerID) REFERENCES PLAYER(ID)
);

CREATE TABLE PLAYER_MATCH_STATS
(
  MinutesPlayed INT NOT NULL CHECK (MinutesPlayed >= 0),
  DistanceCovered NUMERIC(5,2) NOT NULL CHECK (DistanceCovered >= 0),
  MatchID INT NOT NULL,
  PlayerID INT NOT NULL,
  PRIMARY KEY (MatchID, PlayerID),
  FOREIGN KEY (MatchID) REFERENCES MATCHES(MatchID),
  FOREIGN KEY (PlayerID) REFERENCES PLAYER(ID)
);