import csv

# הגדרת שמות הקבצים
input_csv = 'results.csv'
output_sql = 'insertTables.sql'

# פתיחת קובץ ה-CSV לקריאה וקובץ ה-SQL לכתיבה
with open(input_csv, mode='r', encoding='utf-8') as csv_file, \
     open(output_sql, mode='w', encoding='utf-8') as sql_file:
    
    # שימוש ב-DictReader מאפשר לנו לפנות לעמודות לפי השם שלהן בקובץ
    reader = csv.DictReader(csv_file)
    
    # כתיבת הערה בתחילת הקובץ שנוצר
    sql_file.write("-- Script generated by Python for DB Project\n")
    
    count = 0
    
    for row in reader:
        # חילוץ הנתונים מהשורה. נשתמש ב-replace כדי להכפיל גרשיים בודדים, למנוע שגיאות SQL
        match_date = row['date']
        home_team = row['home_team'].replace("'", "''")
        away_team = row['away_team'].replace("'", "''")
        home_score = row['home_score']
        away_score = row['away_score']
        tournament = row['tournament'].replace("'", "''")
        city = row['city'].replace("'", "''")
        country = row['country'].replace("'", "''")
        
        # יצירת פקודת ה-INSERT. שים לב שמחרוזות ותאריכים עטופים בגרש בודד, ומספרים לא
        sql_query = f"INSERT INTO Matches (match_date, home_team, away_team, home_score, away_score, tournament, city, country) VALUES ('{match_date}', '{home_team}', '{away_team}', {home_score}, {away_score}, '{tournament}', '{city}', '{country}');\n"
        
        # כתיבת השאילתה לקובץ ה-SQL
        sql_file.write(sql_query)
        count += 1

print(f"Success! Generated {count} INSERT statements into {output_sql}.")