CREATE OR REPLACE PROCEDURE sp_match_delete(p_mid INT) LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM MATCH_EVENT WHERE MatchID = p_mid;
  DELETE FROM PLAYER_MATCH_STATS WHERE MatchID = p_mid;
  DELETE FROM MATCH WHERE MatchID = p_mid;
END $$;
