CREATE OR REPLACE PROCEDURE sp_player_delete(p_id INT) LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM MATCH_EVENT WHERE ID = p_id;
  DELETE FROM PLAYER_MATCH_STATS WHERE PlayerID = p_id;
  DELETE FROM PLAYER WHERE ID = p_id;
  DELETE FROM PERSON WHERE ID = p_id;
END $$;
