DROP TABLE IF EXISTS MATCH_EVENT CASCADE;
DROP TABLE IF EXISTS PLAYER_MATCH_STATS CASCADE;
DROP TABLE IF EXISTS MATCH CASCADE;
DROP TABLE IF EXISTS PLAYER CASCADE;
DROP TABLE IF EXISTS REFEREE CASCADE;
DROP TABLE IF EXISTS PERSON CASCADE;
DROP TABLE IF EXISTS TEAM CASCADE;
DROP TABLE IF EXISTS STADIUM CASCADE;

CREATE TABLE PERSON
(
  ID VARCHAR(50) NOT NULL,
  FamilyName TEXT,
  GivenName TEXT NOT NULL,
  WikipediaPage TEXT,
  PRIMARY KEY (ID)
);

CREATE TABLE TEAM
(
  TeamCode VARCHAR(50) NOT NULL,
  CountryName TEXT NOT NULL,
  ConfederationName TEXT NOT NULL,
  ConfederationCode VARCHAR(50) NOT NULL,
  WikipediaPage TEXT,
  PRIMARY KEY (TeamCode)
);

CREATE TABLE PLAYER
(
  DateOfBirth DATE,
  TeamCode VARCHAR(50),
  ID VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (TeamCode) REFERENCES TEAM(TeamCode),
  FOREIGN KEY (ID) REFERENCES PERSON(ID)
);

CREATE TABLE REFEREE
(
  Country TEXT NOT NULL,
  ConfederationCode VARCHAR(50) NOT NULL,
  ConfederationName TEXT NOT NULL,
  ID VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES PERSON(ID)
);

CREATE TABLE STADIUM
(
  StadiumID VARCHAR(50) NOT NULL,
  City TEXT NOT NULL,
  Name TEXT NOT NULL,
  Capacity INT NOT NULL,
  WikipediaPage TEXT,
  Country TEXT NOT NULL,
  PRIMARY KEY (StadiumID)
);

CREATE TABLE MATCH
(
  MatchID VARCHAR(50) NOT NULL,
  MatchDate DATE NOT NULL,
  Stage TEXT NOT NULL,
  Tournament TEXT NOT NULL,
  MatchTime TIME,
  StadiumID VARCHAR(50) NOT NULL,
  GuestTeamCode VARCHAR(50) NOT NULL,
  HomeTeamCode VARCHAR(50) NOT NULL,
  RefereeID VARCHAR(50) NOT NULL,
  PRIMARY KEY (MatchID),
  FOREIGN KEY (StadiumID) REFERENCES STADIUM(StadiumID),
  FOREIGN KEY (GuestTeamCode) REFERENCES TEAM(TeamCode),
  FOREIGN KEY (HomeTeamCode) REFERENCES TEAM(TeamCode),
  FOREIGN KEY (RefereeID) REFERENCES REFEREE(ID)
);

CREATE TABLE MATCH_EVENT
(
  Minute TEXT NOT NULL,
  EventType TEXT NOT NULL,
  MatchEventID VARCHAR(50) NOT NULL,
  MatchID VARCHAR(50) NOT NULL,
  ID VARCHAR(50) NOT NULL,
  PRIMARY KEY (MatchEventID),
  FOREIGN KEY (MatchID) REFERENCES MATCH(MatchID),
  FOREIGN KEY (ID) REFERENCES PLAYER(ID)
);

CREATE TABLE PLAYER_MATCH_STATS
(
  Position TEXT NOT NULL,
  ShirtNumber INT NOT NULL,
  MatchID VARCHAR(50) NOT NULL,
  PlayerID VARCHAR(50) NOT NULL,
  PRIMARY KEY (MatchID, PlayerID),
  FOREIGN KEY (MatchID) REFERENCES MATCH(MatchID),
  FOREIGN KEY (PlayerID) REFERENCES PLAYER(ID)
);