CREATE TABLE PERSON
(
  ID INT NOT NULL,
  Name VARCHAR NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE TEAM
(
  TeamCode INT NOT NULL,
  CountryName VARCHAR NOT NULL,
  Confederation VARCHAR NOT NULL,
  PRIMARY KEY (TeamCode)
);

CREATE TABLE PLAYER
(
  Position VARCHAR NOT NULL,
  DateOfBirth VARCHAR NOT NULL,
  TeamCode INT NOT NULL,
  ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (TeamCode) REFERENCES TEAM(TeamCode),
  FOREIGN KEY (ID) REFERENCES PERSON(ID)
);

CREATE TABLE REFEREE
(
  Years_of_experience INT NOT NULL,
  ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES PERSON(ID)
);

CREATE TABLE STADIUM
(
  StadiumID INT NOT NULL,
  City VARCHAR NOT NULL,
  Name VARCHAR NOT NULL,
  Capacity INT NOT NULL,
  PRIMARY KEY (StadiumID)
);

CREATE TABLE MATCH
(
  MatchID INT NOT NULL,
  MatchDate VARCHAR NOT NULL,
  Stage VARCHAR NOT NULL,
  HomeTeamCode INT NOT NULL,
  AwayTeamCode INT NOT NULL,
  StadiumID INT NOT NULL,
  RefereeID INT NOT NULL,
  PRIMARY KEY (MatchID),
  FOREIGN KEY (HomeTeamCode) REFERENCES TEAM(TeamCode),
  FOREIGN KEY (AwayTeamCode) REFERENCES TEAM(TeamCode),
  FOREIGN KEY (StadiumID) REFERENCES STADIUM(StadiumID),
  FOREIGN KEY (RefereeID) REFERENCES REFEREE()
);

CREATE TABLE MATCH_EVENT
(
  Minute INT NOT NULL,
  EventType VARCHAR NOT NULL,
  MatchID INT NOT NULL,
  PlayerID INT NOT NULL,
  PRIMARY KEY (Minute, MatchID),
  FOREIGN KEY (MatchID) REFERENCES MATCH(MatchID),
  FOREIGN KEY (PlayerID) REFERENCES PLAYER()
);

CREATE TABLE PLAYER_MATCH_STATS
(
  MinutesPlayed INT NOT NULL,
  DistanceCovered INT NOT NULL,
  MatchID INT NOT NULL,
  PlayerID INT NOT NULL,
  PRIMARY KEY (MatchID),
  FOREIGN KEY (MatchID) REFERENCES MATCH(MatchID),
  FOREIGN KEY (PlayerID) REFERENCES PLAYER()
);