DROP TABLE IF EXISTS MATCH_EVENT CASCADE;
DROP TABLE IF EXISTS PLAYER_MATCH_STATS CASCADE;
DROP TABLE IF EXISTS MATCHES CASCADE;
DROP TABLE IF EXISTS PLAYER CASCADE;
DROP TABLE IF EXISTS REFEREE CASCADE;
DROP TABLE IF EXISTS PERSON CASCADE;
DROP TABLE IF EXISTS TEAM CASCADE;
DROP TABLE IF EXISTS STADIUM CASCADE;